[package]
name = "stockfighter"
version = "0.1.0"
authors = ["Aaron Mell <aaronamell@gmail.com>"]

[dependencies]
hyper = "0.8.1"
rustc-serialize = "0.3"

[dependencies.docopt]
git = "https://github.com/kindlychung/docopt.rs"
rev = "e16e44aa126dad9d29e564c23e65ab102f2611a0"
